#!/usr/bin/env python3
"""apply_theta_{ST_CODE}_perspecies.py — write theta-scaled SppEcoregionData.csv.

GENERATED by add_state.sh from apply_theta_template.py (cluster {CLUSTER}).
State-agnostic: multipliers are looked up by SpeciesCode from the theta CSV and applied
to the baseline SppEcoregionData rows. A species present in the baseline but absent from
the theta vector is left unscaled (multiplier 1.0), so a partial warmstart reference is
safe. Theta CSV format: header 'param,value' with params ANPP_<sp> and BMAX_<sp>.
"""
import argparse, csv, sys

def read_theta(path):
    mult = {}
    with open(path) as f:
        reader = csv.DictReader(f)
        if reader.fieldnames and "param" in reader.fieldnames and "value" in reader.fieldnames:
            for row in reader:
                try:
                    mult[row["param"]] = float(row["value"])
                except (KeyError, ValueError):
                    pass
        else:
            sys.stderr.write("ERROR: theta CSV must have 'param,value' header\n")
            sys.exit(1)
    return mult

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--theta-csv", required=True)
    p.add_argument("--baseline-spp", required=True)
    p.add_argument("--out", required=True)
    args = p.parse_args()
    mult = read_theta(args.theta_csv)
    n_scaled = 0
    with open(args.baseline_spp) as f, open(args.out, "w", newline="") as g:
        rdr = csv.DictReader(f)
        w = csv.DictWriter(g, fieldnames=rdr.fieldnames); w.writeheader()
        for r in rdr:
            sp = r["SpeciesCode"]
            a = mult.get(f"ANPP_{sp}", 1.0)
            b = mult.get(f"BMAX_{sp}", 1.0)
            if a != 1.0 or b != 1.0:
                n_scaled += 1
            try:
                r["ANPPmax"] = str(int(round(float(r["ANPPmax"]) * a)))
                r["BiomassMax"] = str(int(round(float(r["BiomassMax"]) * b)))
            except (KeyError, ValueError):
                pass
            w.writerow(r)
    sys.stderr.write(f"apply_theta: scaled {n_scaled} species rows -> {args.out}\n")

if __name__ == "__main__":
    main()
