#!/bin/bash
# build_plot_scenario_{ST_CODE}.sh   (GENERATED by add_state.sh from build_plot_scenario_template.sh)
#
# Build a single-plot LANDIS-II scenario directory for a {ST_CODE} PERSEUS plot
# (cluster {CLUSTER}). 1-cell landscape, FIA-derived IC, restricted to the plot's
# EPA L3 ecoregion.
#
# State-agnostic redesign of build_plot_scenario_MN.sh:
#   * ecoregion NAME is looked up from the state's own inputs/ecoregions.txt (no
#     hardcoded per-state case table);
#   * the Output Biomass species block is generated from inputs/SpeciesData.csv, so it
#     always matches the state's species pool;
#   * climate is taken from $CLIM_BASELINE (default below). NOTE: the climate transpose
#     assumes the MN long-format template (Year,Month,EcoregionId,tmin,tmax,precip).
#     VERIFY this section against the cluster's climate format with a single smoke run
#     (add_state.sh ... dry, then build + run one plot) before launching a full chain.
#
# Usage: bash build_plot_scenario_{ST_CODE}.sh <PLOT_ID> <baseline> <none|perseus>
set -euo pipefail
if [ "$#" -lt 3 ]; then
  echo "Usage: bash build_plot_scenario_{ST_CODE}.sh <PLOT_ID> <baseline> <none|perseus>"; exit 1
fi
PLOT=$1; CLIM=$2; HARV=$3

LANDIS=/fs/scratch/PUOM0008/crsfaaron/landis2
STATE=$LANDIS/states/{ST_CODE}
INPUTS=$STATE/inputs
ICS=$STATE/perseus/plot_ics_full
RUNS=$STATE/perseus/runs
TOOLS=$LANDIS/tools
SIF=$LANDIS/images/landis-ii_v8_allext_v1.0.sif
PLOT_ECO_CSV=$TOOLS/plot_to_ecoregion_{ST_CODE}.csv
# Climate template (long format). Override by exporting CLIM_BASELINE before calling.
CLIM_BASELINE=${CLIM_BASELINE:-$INPUTS/climate_template.csv}
AET_MM=${AET_MM:-550}

PLOT_DIR=$RUNS/plot_${PLOT}__clim_${CLIM}_harv_${HARV}
IC_SOURCE=$ICS/plot_${PLOT}/initial_communities.csv
[ -f "$IC_SOURCE" ] || { echo "ERROR: missing IC csv at $IC_SOURCE"; exit 2; }
[ -f "$PLOT_ECO_CSV" ] || { echo "ERROR: missing $PLOT_ECO_CSV"; exit 3; }

RAW_ECO=$(awk -F',' -v p="$PLOT" 'NR>1 && $1==p {print $3}' "$PLOT_ECO_CSV" | tr -d '\r\n ')
[ -z "$RAW_ECO" ] && { echo "ERROR: plot $PLOT not in $PLOT_ECO_CSV"; exit 4; }
[ "$RAW_ECO" = "0" ] && { echo "SKIP: plot $PLOT is in eco 0 (nodata)"; exit 5; }
ECO=$RAW_ECO
# Ecoregion name from the state's own ecoregions.txt (mapcode match); fall back to code.
ECO_NAME=$(awk -v e="$ECO" '$0 !~ /^>>/ && $2==e {name=$3; for(i=4;i<=NF;i++) name=name" "$i; print name; exit}' "$INPUTS/ecoregions.txt" 2>/dev/null)
[ -z "$ECO_NAME" ] && ECO_NAME="\"eco_$ECO\""

mkdir -p "$PLOT_DIR"

# 1. IC csv
cp "$IC_SOURCE" "$PLOT_DIR/initial-communities.csv"

# 2. Single-ecoregion ecoregions.txt
cat > "$PLOT_DIR/ecoregions.txt" <<EOF
LandisData "Ecoregions"
>>Active	MapCode	Name	Description
no	0	nodata	"non-forest"
yes	$ECO	$ECO	$ECO_NAME
EOF

# 3. 1x1 ecoregion + IC rasters
apptainer exec --bind /fs/scratch/PUOM0008:/fs/scratch/PUOM0008 $SIF python3 - <<PY
from osgeo import gdal
import numpy as np
ds = gdal.GetDriverByName('GTiff').Create('$PLOT_DIR/ecoregions.tif', 1, 1, 1, gdal.GDT_Int32, options=['COMPRESS=DEFLATE'])
ds.GetRasterBand(1).WriteArray(np.array([[$ECO]], dtype=np.int32)); ds.GetRasterBand(1).SetNoDataValue(0)
ds.SetGeoTransform([0.0, 30.0, 0.0, 30.0, 0.0, -30.0]); ds = None
ds = gdal.GetDriverByName('GTiff').Create('$PLOT_DIR/initial-communities.tif', 1, 1, 1, gdal.GDT_Int32, options=['COMPRESS=DEFLATE'])
ds.GetRasterBand(1).WriteArray(np.array([[1]], dtype=np.int32)); ds.GetRasterBand(1).SetNoDataValue(0)
ds.SetGeoTransform([0.0, 30.0, 0.0, 30.0, 0.0, -30.0]); ds = None
PY

# 4. species + SpeciesData symlinks
ln -sf $INPUTS/species.txt     "$PLOT_DIR/species.txt"
ln -sf $INPUTS/SpeciesData.csv "$PLOT_DIR/SpeciesData.csv"

# 5. SppEcoregionData filtered to this ECO
head -1 $INPUTS/SppEcoregionData.csv > "$PLOT_DIR/SppEcoregionData.csv"
awk -F',' -v e="$ECO" 'NR>1 && $2==e' $INPUTS/SppEcoregionData.csv >> "$PLOT_DIR/SppEcoregionData.csv"

# 6. climate.csv: transpose long format (Year,Month,EcoregionId,tmin,tmax,precip) to the
#    LANDIS Climate Library Monthly format (Year,Month,Variable,<ECO>). Nearest-neighbor
#    fallback to the first available ecoregion if $ECO has no rows.
SRC_ECO=$ECO
if ! awk -F',' -v e="$ECO" 'NR>1 && $3==e{f=1} END{exit !f}' "$CLIM_BASELINE"; then
  SRC_ECO=$(awk -F',' 'NR>1{print $3; exit}' "$CLIM_BASELINE")
fi
awk -F',' -v e="$ECO" -v se="$SRC_ECO" 'BEGIN{OFS=","; print "Year","Month","Variable",e}
  NR>1 && $3==se { print $1,$2,"precip",$6; print $1,$2,"mintemp",$4; print $1,$2,"maxtemp",$5 }' \
  "$CLIM_BASELINE" > "$PLOT_DIR/climate.csv"

cat > "$PLOT_DIR/climate-generator.txt" <<EOF
LandisData "Climate Config"
ClimateTimeSeries          Monthly_AverageAllYears
ClimateFile                climate.csv
SpinUpClimateTimeSeries    Monthly_AverageAllYears
SpinUpClimateFile          climate.csv
GenerateClimateOutputFiles yes
UsingFireClimate           no
EOF

# 7. biomass-succession.txt restricted to single ECO
cat > "$PLOT_DIR/biomass-succession.txt" <<EOF
LandisData "Biomass Succession"

Timestep             5
SeedingAlgorithm     WardSeedDispersal
InitialCommunities       initial-communities.csv
InitialCommunitiesMap    initial-communities.tif
ClimateConfigFile        climate-generator.txt

MinRelativeBiomass
>> Shade  Percent Max Biomass per ecoregion
        $ECO
    1  20%
    2  40%
    3  60%
    4  80%
    5  100%

SufficientLight
>>  Spp Shade  Probability by Actual Shade
>>             0    1    2    3    4    5
    1   1.0  0.5  0.0  0.0  0.0  0.0
    2   1.0  1.0  0.5  0.0  0.0  0.0
    3   1.0  1.0  1.0  0.5  0.0  0.0
    4   1.0  1.0  1.0  1.0  0.5  0.0
    5   1.0  1.0  1.0  1.0  1.0  0.5

SpeciesDataFile        SpeciesData.csv

EcoregionParameters
>>  AET (mm)
$ECO   $AET_MM

SpeciesEcoregionDataFile  SppEcoregionData.csv

FireReductionParameters
>>  Severity   WoodLitter   Litter
    1          0.0          0.5
    2          0.0          0.75
    3          0.5          1.0

HarvestReductionParameters
>>  Name             WoodLitter  Litter  Cohort_Wood  Cohort_Leaf
    PerseusBA50      0.5         0.15    0.5          0.0
EOF

# 8. output-biomass.txt — species block generated from this state's SpeciesData.csv.
{
  echo 'LandisData  "Output Biomass"'
  echo 'Timestep   5'
  echo 'MakeTable  yes'
  awk -F',' 'NR>1 && $1!="" { if (first==0){ printf "Species  %s\n", $1; first=1 } else { printf "         %s\n", $1 } }' "$INPUTS/SpeciesData.csv"
  echo 'MapNames   output/biomass/biomass-{species}-{timestep}.tif'
  echo 'DeadPools  both'
  echo 'MapNames   output/biomass/biomass-{pool}-{timestep}.tif'
} > "$PLOT_DIR/output-biomass.txt"

# 9. scenario.txt (no harvest for calibration; duration 100)
cat > "$PLOT_DIR/scenario.txt" <<EOF
LandisData  Scenario

Duration   100
Species    species.txt
Ecoregions ecoregions.txt
EcoregionsMap ecoregions.tif
CellLength    30

"Biomass Succession"   biomass-succession.txt
"Output Biomass"       output-biomass.txt

RandomNumberSeed   42
EOF

mkdir -p "$PLOT_DIR/output/biomass"
echo "Built {ST_CODE} scenario at $PLOT_DIR (eco $ECO from raw $RAW_ECO)"
